name: openstack-charms-cert-validator
summary: Validate an ssl cert chain for openstack charms
description: |
  A small tool to validate an SSL certificate chain for openstack charms.

  Docs available at https://github.com/canonical/openstack-charms-cert-validator
version: "0.1"
license: GPL-3.0
grade: stable
confinement: strict
base: core22
source-code: https://github.com/canonical/openstack-charms-cert-validator
architectures:
  - build-on:
    - amd64

apps:
  openstack-charms-cert-validator:
    command: bin/openstack-charms-cert-validator
    plugs:
      - home
      - network
    environment:
      PYTHONPATH: $SNAP

parts:
  validatecert:
    plugin: nil
    source: .
    build-packages:
      - python3-pip
    override-build: |
      pip install -t $CRAFT_PART_INSTALL .
